version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_USER=vmw_ghost
      - MARIADB_DATABASE=vmware_ghost
      - MARIADB_PASSWORD=dbpassword
      - MARIADB_ROOT_PASSWORD=dbpassword
  ghost:
    image: docker.io/bitnami/ghost:4
    ports:
      - '80:2368'
    volumes:
      - 'ghost_data:/bitnami/ghost'
    depends_on:
      - mariadb
    environment:
      - GHOST_DATABASE_HOST=mariadb
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=vmw_ghost
      - GHOST_DATABASE_NAME=vmware_ghost
      - GHOST_DATABASE_PASSWORD=dbpassword
volumes:
  mariadb_data:
    driver: local
  ghost_data:
    driver: local
